### PR TITLE
Enforce UTF8 encoding

### PR DESCRIPTION
**Pull request by tiagojsalmeida**

### CODE REVIEW

**Comment by casperdcl** [comment]
Sorry but not sure... what does this fix?

**Comment by tiagojsalmeida** [comment]
Hey there!
When having user first & last names with special characters, the `--formatCSV` export wasn't really working due to encoding.

**Comment by casperdcl** [comment]
But changing `setup.py` fixes this? How?

**Comment by tiagojsalmeida** [comment]
Just making sure that the default encoding is UTF-8 basically.
I grabbed the solution from here: https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python

But for full transparency I'm not a python guro! Is there a better way to solve it?

**Comment by casperdcl** [comment]
I don't know; never seen it before. I'm pretty sure this fix won't work (and is not needed) in py3, but perhaps it's needed in py2? Still seems really strange that `setup.py` rather than `_gitfame.py` needs changing.

**Comment by tiagojsalmeida** [comment]
Yeah i changed it locally and that fixed it. It might be an user error (me) so I will just close this :)

**Pull request closed without merging**
